# Generated by Django 5.2.7 on 2025-11-18 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
